"""add phone number

Revision ID: 5bbb1e174a8b
Revises: a8c8a8f9610c
Create Date: 2022-09-16 11:53:26.243482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbb1e174a8b'
down_revision = 'a8c8a8f9610c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
